usr/lib/${DEB_HOST_MULTIARCH}/qt5/qml/Qt/test/qtestroot/plugins.qmltypes
usr/lib/${DEB_HOST_MULTIARCH}/qt5/qml/Qt/test/qtestroot/qmldir
usr/lib/${DEB_HOST_MULTIARCH}/qt5/qml/QtTest/SignalSpy.qml
usr/lib/${DEB_HOST_MULTIARCH}/qt5/qml/QtTest/TestCase.qml
usr/lib/${DEB_HOST_MULTIARCH}/qt5/qml/QtTest/libqmltestplugin.so
usr/lib/${DEB_HOST_MULTIARCH}/qt5/qml/QtTest/plugins.qmltypes
usr/lib/${DEB_HOST_MULTIARCH}/qt5/qml/QtTest/qmldir
usr/lib/${DEB_HOST_MULTIARCH}/qt5/qml/QtTest/testlogger.js
